In [2]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

In [10]:
dataset=pd.read_csv('Datasets/sonar.csv',header=None)

In [11]:
dataset.head()

0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [13]:
dataset.shape

(208, 61)

In [14]:
#check null
dataset.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [15]:
X= dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [21]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [20]:
y

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [23]:
y=pd.get_dummies(y,drop_first=True)

In [25]:
y.head()

R
0  1
1  1
2  1
3  1
4  1

In [26]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)

In [29]:
X_test.shape

(42, 60)

In [30]:
X_train.shape


(166, 60)

In [77]:
model= keras.Sequential([
    keras.layers.Dense(60,input_shape=(60,),activation='relu'),
    keras.layers.Dense(1000,activation='relu'),

    keras.layers.Dense(1,activation='sigmoid')
])

In [78]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']

)

In [79]:
model.fit(X_train,y_train,epochs=70
         )

Epoch 1/70
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
6/6 [==============================] - 0s 709us/step - loss: 0.6903 - accuracy: 0.5340
Epoch 2/70
6/6 [==============================] - 0s 623us/step - loss: 0.6606 - accuracy: 0.5496
Epoch 3/70
6/6 [==============================] - 0s 807us/step - loss: 0.6307 - accuracy: 0.6953
Epoch 4/70
6/6 [==============================] - 0s 796us/step - loss: 

In [81]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 2ms/step - loss: 0.6143 - accuracy: 0.8810


[0.614290714263916, 0.8809523582458496]

In [83]:
y_pred = model.predict(X_test)

In [87]:
y_pred[:3]


array([[0.01047165],
       [0.90882194],
       [0.00947941]], dtype=float32)

In [91]:
y_pred=np.round(y_pred)
y_pred[:3]

array([[0.],
       [1.],
       [0.]], dtype=float32)

In [95]:
y_test[:3].values

array([[1],
       [1],
       [1]], dtype=uint8)

In [92]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.95      0.89        21
           1       0.94      0.81      0.87        21

    accuracy                           0.88        42
   macro avg       0.89      0.88      0.88        42
weighted avg       0.89      0.88      0.88        42




## Dropout Layer

In [120]:
model= keras.Sequential([
    keras.layers.Dense(60,input_shape=(60,),activation='relu'),
   
    keras.layers.Dense(100,activation='relu'),
       keras.layers.Dropout(0.2),
    keras.layers.Dense(100,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])

In [121]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_49 (Dense)             (None, 60)                3660      
_________________________________________________________________
dense_50 (Dense)             (None, 100)               6100      
_________________________________________________________________
dropout_6 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_51 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_52 (Dense)             (None, 1)                 101       
Total params: 19,961
Trainable params: 19,961
Non-trainable params: 0
_________________________________________________________________


In [122]:

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']

)

In [123]:
model.fit(X_train,y_train,epochs=70
         )

Epoch 1/70
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
6/6 [==============================] - 0s 660us/step - loss: 0.6811 - accuracy: 0.5740
Epoch 2/70
6/6 [==============================] - 0s 547us/step - loss: 0.6668 - accuracy: 0.6074
Epoch 3/70
6/6 [==============================] - 0s 581us/step - loss: 0.6644 - accuracy: 0.6615
Epoch 4/70
6/6 [==============================] - 0s 897us/step - loss: 

In [125]:
model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 1ms/step - loss: 2.0411 - accuracy: 0.5476


[2.041119337081909, 0.5476190447807312]

In [126]:
#supposed to increase test metrics