In [4]:
import numpy as np
import math
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib as plt
%matplotlib inline

In [33]:
dataset= pd.read_csv('Social_Network_Ads.csv')

In [34]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [35]:
X = dataset.iloc[:,0:3].values
y = dataset.iloc[:,-1].values

In [37]:
dataset.iloc[:,-1]

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)


In [39]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
X_train

array([[ 1.92295008e+00,  2.14601566e+00,  1.28243054e+00],
       [ 2.02016082e+00,  3.78719297e-01, -7.79769326e-01],
       [-1.38221530e+00, -4.32498705e-01, -7.79769326e-01],
       [-1.18779381e+00, -1.01194013e+00, -7.79769326e-01],
       [ 1.92295008e+00, -9.25023920e-01,  1.28243054e+00],
       [ 3.67578135e-01,  2.91803083e-01,  1.28243054e+00],
       [ 1.73156642e-01,  1.46942725e-01, -7.79769326e-01],
       [ 2.02016082e+00,  1.74040666e+00,  1.28243054e+00],
       [ 7.56421121e-01, -8.38107706e-01,  1.28243054e+00],
       [ 2.70367388e-01, -2.87638347e-01, -7.79769326e-01],
       [ 3.67578135e-01, -1.71750061e-01, -7.79769326e-01],
       [-1.18475597e-01,  2.20395980e+00,  1.28243054e+00],
       [-1.47942605e+00, -6.35303205e-01, -7.79769326e-01],
       [-1.28500455e+00, -1.06988428e+00, -7.79769326e-01],
       [-1.38221530e+00,  4.07691369e-01, -7.79769326e-01],
       [-1.09058306e+00,  7.55356227e-01,  1.28243054e+00],
       [-1.47942605e+00, -2.00722133e-01

In [54]:
model=tf.keras.Sequential([
    keras.layers.Dense(1,activation= 'sigmoid',kernel_initializer = 'ones',bias_initializer='zeros'),

                       ])

In [55]:
model.compile(optimizer='adam', loss = "binary_crossentropy",metrics='accuracy')

In [56]:
model.fit(X_train,y_train,epochs=70)

Epoch 1/70
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
10/10 [==============================] - 0s 356us/step - loss: 0.2621 - accuracy: 0.9611
Epoch 2/70
10/10 [==============================] - 0s 350us/step - loss: 0.2422 - accuracy: 0.9408
Epoch 3/70
10/10 [==============================] - 0s 405us/step - loss: 0.2389 - accuracy: 0.9439
Epoch 4/70
10/10 [==============================] - 0s 387us/step 

In [57]:
model.evaluate(X_test,y_test)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
3/3 [==============================] - 0s 630us/step - loss: 0.0792 - accuracy: 1.0000


[0.0791957676410675, 1.0]

In [58]:
coef, intercepts = model.get_weights()
coef

array([[1.136335 ],
       [0.7236735],
       [1.6098249]], dtype=float32)