In [2]:
import numpy as np
import math
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib as plt
%matplotlib inline

In [3]:
dataset= pd.read_csv('../Datasets/Social_Network_Ads.csv')

In [4]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:
X = dataset.iloc[:,0:3].values
y = dataset.iloc[:,-1].values

In [6]:
dataset.iloc[:,-1]

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)


In [8]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[ 1.92295008e+00,  2.14601566e+00,  1.28243054e+00],
       [ 2.02016082e+00,  3.78719297e-01, -7.79769326e-01],
       [-1.38221530e+00, -4.32498705e-01, -7.79769326e-01],
       [-1.18779381e+00, -1.01194013e+00, -7.79769326e-01],
       [ 1.92295008e+00, -9.25023920e-01,  1.28243054e+00],
       [ 3.67578135e-01,  2.91803083e-01,  1.28243054e+00],
       [ 1.73156642e-01,  1.46942725e-01, -7.79769326e-01],
       [ 2.02016082e+00,  1.74040666e+00,  1.28243054e+00],
       [ 7.56421121e-01, -8.38107706e-01,  1.28243054e+00],
       [ 2.70367388e-01, -2.87638347e-01, -7.79769326e-01],
       [ 3.67578135e-01, -1.71750061e-01, -7.79769326e-01],
       [-1.18475597e-01,  2.20395980e+00,  1.28243054e+00],
       [-1.47942605e+00, -6.35303205e-01, -7.79769326e-01],
       [-1.28500455e+00, -1.06988428e+00, -7.79769326e-01],
       [-1.38221530e+00,  4.07691369e-01, -7.79769326e-01],
       [-1.09058306e+00,  7.55356227e-01,  1.28243054e+00],
       [-1.47942605e+00, -2.00722133e-01

In [11]:
model=tf.keras.Sequential([
    keras.layers.Dense(1,activation= 'sigmoid',kernel_initializer = 'ones',bias_initializer='zeros'),

                       ])

In [12]:
model.compile(optimizer='adam', loss = "binary_crossentropy",metrics='accuracy')

In [13]:
model.fit(X_train,y_train,epochs=70)

Epoch 1/70
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
10/10 [==============================] - 0s 349us/step - loss: 0.2484 - accuracy: 0.9478
Epoch 2/70
10/10 [==============================] - 0s 300us/step - loss: 0.2304 - accuracy: 0.9610
Epoch 3/70
10/10 [==============================] - 0s 295us/step - loss: 0.2244 - accuracy: 0.9673
Epoch 4/70
10/10 [==============================] - 0s 382us/step 

2022-07-09 13:09:37.985662: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-07-09 13:09:37.989337: W tensorflow/core/platform/profile_utils/cpu_utils.cc:126] Failed to get CPU frequency: 0 Hz


Epoch 5/70
10/10 [==============================] - 0s 367us/step - loss: 0.2101 - accuracy: 0.9616
Epoch 6/70
10/10 [==============================] - 0s 416us/step - loss: 0.2415 - accuracy: 0.9486
Epoch 7/70
10/10 [==============================] - 0s 316us/step - loss: 0.2021 - accuracy: 0.9645
Epoch 8/70
10/10 [==============================] - 0s 413us/step - loss: 0.2055 - accuracy: 0.9683
Epoch 9/70
10/10 [==============================] - 0s 351us/step - loss: 0.2001 - accuracy: 0.9706
Epoch 10/70
10/10 [==============================] - 0s 420us/step - loss: 0.2093 - accuracy: 0.9573
Epoch 11/70
10/10 [==============================] - 0s 446us/step - loss: 0.2048 - accuracy: 0.9657
Epoch 12/70
10/10 [==============================] - 0s 351us/step - loss: 0.2311 - accuracy: 0.9486
Epoch 13/70
10/10 [==============================] - 0s 402us/step - loss: 0.2214 - accuracy: 0.9606
Epoch 14/70
10/10 [==============================] - 0s 361us/step - loss: 0.1830 - accuracy: 0.

In [14]:
model.evaluate(X_test,y_test)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
3/3 [==============================] - 0s 558us/step - loss: 0.0793 - accuracy: 1.0000


[0.07933421432971954, 1.0]

In [15]:
coef, intercepts = model.get_weights()
coef

array([[1.1365203],
       [0.7245433],
       [1.6104527]], dtype=float32)

In [17]:
model.predict(X_test)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unsupported operand type(s) for -: 'NoneType' and 'int'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


array([[0.08930133],
       [0.09840923],
       [0.11694496],
       [0.07655314],
       [0.07266386],
       [0.01695531],
       [0.023589  ],
       [0.9457456 ],
       [0.01717767],
       [0.2030032 ],
       [0.0422949 ],
       [0.03860927],
       [0.09792016],
       [0.17685924],
       [0.03082835],
       [0.18671684],
       [0.14694858],
       [0.02713342],
       [0.99065536],
       [0.041717  ],
       [0.06853293],
       [0.98326856],
       [0.1344016 ],
       [0.96284956],
       [0.01294432],
       [0.9856786 ],
       [0.07288735],
       [0.07046172],
       [0.1116884 ],
       [0.10695551],
       [0.03572444],
       [0.83262146],
       [0.96817374],
       [0.09427381],
       [0.0267569 ],
       [0.01233768],
       [0.03448955],
       [0.05711409],
       [0.03474809],
       [0.88365114],
       [0.06706643],
       [0.13686253],
       [0.06199997],
       [0.04007057],
       [0.9507308 ],
       [0.03688401],
       [0.15501952],
       [0.970